# Book settings
# Full _config.yml defaults at https://jupyterbook.org/customize/config.html

title: Portfolio
author: Adam Wang
copyright: "2021"
only_build_toc_files: true

execute:
  execute_notebooks: auto

parse:
  myst_enable_extensions:
    - dollarmath
    - amsmath

launch_buttons:
  notebook_interface: "classic"
  binderhub_url: "https://mybinder.org"
  thebe: true

repository:
  url: https://github.com/adamwangdata/adamwangdata.github.io
  branch: main

sphinx:
  config:
    nb_custom_formats:
      # Enable Python and R files to be source documents
      .py:
        - jupytext.reads
        - fmt: py
      .r:
        - jupytext.reads
        - fmt: r
    mathjax_config:
      TeX:
        Macros:
          "parens": ["\\mathopen{}\\left(#1\\right)\\mathclose{}", 1]
          "bracks": ["\\mathopen{}\\left[#1\\right]\\mathclose{}", 1]
          "braces": ["\\mathopen{}\\left\\{#1\\right\\}\\mathclose{}", 1]
          "abs": ["\\mathopen{}\\left\\lvert#1\\right\\rvert\\mathclose{}", 1]
          "norm": ["\\mathopen{}\\left\\lVert#1\\right\\rVert\\mathclose{}", 1]
          "vec": ["\\boldsymbol{\\mathbf{#1}}", 1]
          "mat": ["\\mathbf{#1}", 1]
          "tpose": ["#1^T", 1]
          "inv": ["#1^{-1}", 1]
          "Matrix": ["\\begin{bmatrix}#1\\end{bmatrix}", 1]
          "seq" : ["1, 2, \\ldots, #1", 1]
          "reals" : ["\\mathbb{R}"]
          "mper" : ["\\,\\text{.}"]
          "mcom" : ["\\,\\text{,}"]