# To update environment based on this file, run
# conda env update --prefix ./env --file binder/environment.yml --prune
channels:
  - conda-forge
dependencies:
  - python=3.7.10
  - numpy=1.20.3
  - cython
  - matplotlib
  - pandas
  - scipy
  - nltk
  - scikit-learn
  - pip
  - pip:
      - pystan==2.19.1.1
      - prophet
      - plotly
      - jupyter-book==0.11.1
      - jinja2==3.0.3
  - r-base
  - r-irkernel
  - r-repr
  - r-faraway
  - r-corrplot
  - r-ggplot2
  - r-gridExtra
  - r-nlme
  - r-glmnet
