# To update environment based on this file, run
# conda env update --prefix ./env --file binder/environment.yml --prune
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - jupytext
  - black
  - pandas
  - numpy
  - scipy
  - matplotlib
  - scikit-learn
  - nltk
  - pystan==2.19.1.1
  - prophet
  - r-base
  - r-irkernel
  - r-repr
  - r-faraway
  - r-corrplot
  - r-ggplot2
  - r-gridExtra
  - r-nlme
  - r-glmnet
