# To update environment based on this file, run
# conda env update --prefix ./env --file binder/environment.yml --prune
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - cython
  - matplotlib
  - pandas
  - scipy
  - pip:
    - pystan==2.19.1.1
    - prophet
    - jupyter-book==0.11.1
